---
title: "Data Preprocessing"
output: pdf_document
---

```{r}
pacman::p_load(tidyverse)
pacman::p_load(bestNormalize)
```


```{r}
DF=read_csv("radiomics_completedata.csv")
OriginalDF=DF
```


```{r}
sum(is.na(DF))
```


```{r,warning=F}
DF1=DF%>%select_if(is.numeric)
DF1=DF1[,-1]
DF2=apply(DF1,2,function(x){ks.test(x,"pnorm")})
```

```{r}
KS_list=unlist(lapply(DF2, function(x) x$p.value))
```


```{r}
sum(KS_list<0.05)
```


```{r}
sum(KS_list>0.05)
```

```{r}
which.max(KS_list)
```

```{r,warning=F}
tempDF=DF[,c(3,5:length(names(DF)))]

tempDF=apply(tempDF,2,orderNorm)
tempDF=lapply(tempDF, function(x) x$x.t)
tempDF=tempDF%>%as.data.frame()
test=apply(tempDF,2,shapiro.test)
test=unlist(lapply(test, function(x) x$p.value))
```


```{r,warning=F}
sum(test>0.05)
```


```{r,warning=F}
sum(test<0.05)
```


```{r}
DF[,c(3,5:length(names(DF)))]=tempDF
```


```{r}
CorMatrix=cor(DF[,-c(1,2)])
heatmap(CorMatrix,Rowv=NA,Colv=NA,scale="none",revC = T)
```


```{r}
DF$Institution=as.factor(DF$Institution)
DF$Failure.binary=as.factor(DF$Failure.binary)
```

```{r}
splitter <- sample(1:nrow(DF), round(nrow(DF) * 0.8))
trainDF <- DF[splitter, ]
testDF  <- DF[-splitter, ]
```

```{r}


par(mfrow=c(1,2))
DF$GLNU_align.H.PET%>%hist()
OriginalDF$GLNU_align.H.PET%>%hist()
par(mfrow=c(1,2))

DF$GLNU_align.H.PET%>%mean()
DF$GLNU_align.H.PET%>%sd()

OriginalDF$GLNU_align.H.PET%>%mean()
OriginalDF$GLNU_align.H.PET%>%sd()

```




